### ISSUE TITLE
How to initial the wallet

### ISSUE THREAD

**Issue by CHOMNANP** [soramitsu/iroha-wallet-js#10]
I have cloned the project but sure how to login and initialize the admin account

**Comment by laSinteZ** [comment]
@CHOMNANP now this wallet isn't officialy released yet, but it is meant to work with Iroha instance. You need to have an Iroha instance working (for example follow http://iroha.readthedocs.io/en/latest/getting_started/) and to have some transactions inside it. you can try https://github.com/soramitsu/iroha-wallet-js/blob/develop/example/setup-accounts-and-assets.js this script to populate the database.

**Comment by neewy** [comment]
Is this issue still relevant?
