### ISSUE TITLE
I can not log in

### ISSUE THREAD

**Issue by kaorunihei** [soramitsu/iroha-wallet-js#29]
Username:admin@iroha
Private Key:0f0ce16d2afbb8eca23c7d8c2724f0c257a800ee2bbd54688cec6b898e3f7e33
Node ID:localhost:8081

When LOGIN button is pressed

LOGIN ERROR
Response closed without headers

**Comment by larryho87** [comment]
hi kaorunihei, possible to share on how to resolve this issue, i am facing the exact issues as you. followed exactly the steps provided in the guide but is unable to login
